version: '2'

services:
    nginxreverseproxy:
        build: ./
        ports:
            - 8080:80
        links:
            - sitea
            - siteb
            - wordpress
            - phpmyadmin
    sitea:
        build: ./siteA
    siteb:
        build: ./siteB
#part B
    db:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: datas
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
        MYSQL_ROOT_PASSWORD: pass
      networks:
        - wpdbnet
    wordpress:
      image: wordpress
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: user
        WORDPRESS_DB_PASSWORD: pass
        WORDPRESS_DB_NAME: datas
      networks:
        - wpdbnet
        - default
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      networks:
        - wpdbnet
        - default

networks:
    wpdbnet:
